const popularJobs = [
  {
    job_id: 1,
    job_title: "Software Engineer",
    job_publisher: "User",
    employer_name: "Tech Company 1",
    job_country: "USA",
    employer_logo: "https://via.placeholder.com/150",
    description: "This is a job description for a software engineer position.",
  },
  {
    job_id: 2,
    job_title: "Data Scientist",
    job_publisher: "User",
    employer_name: "Data Company 2",
    job_country: "USA",
    employer_logo: "https://via.placeholder.com/150",
    description: "This is a job description for a data scientist position.",
  },
  {
    job_id: 3,
    job_title: "Product Manager",
    job_publisher: "User",
    employer_name: "Product Company 3",
    job_country: "USA",
    employer_logo: "https://via.placeholder.com/150",
    description: "This is a job description for a product manager position.",
  },
  {
    job_id: 4,
    job_title: "UX Designer",
    job_publisher: "User",
    employer_name: "Design Company 4",
    job_country: "USA",
    employer_logo: "https://via.placeholder.com/150",
    description: "This is a job description for a UX designer position.",
  },
  {
    job_id: 5,
    job_title: "Frontend Developer",
    job_publisher: "User",
    employer_name: "Tech Company 5",
    job_country: "USA",
    employer_logo: "https://via.placeholder.com/150",
    description: "This is a job description for a frontend developer position.",
  },
  {
    job_id: 6,
    job_title: "Backend Developer",
    job_publisher: "User",
    employer_name: "Tech Company 6",
    job_country: "USA",
    employer_logo: "https://via.placeholder.com/150",
    description: "This is a job description for a backend developer position.",
  },
  {
    job_id: 7,
    job_title: "DevOps Engineer",
    job_publisher: "User",
    employer_name: "Tech Company 7",
    job_country: "USA",
    employer_logo: "https://via.placeholder.com/150",
    description: "This is a job description for a DevOps engineer position.",
  },
  {
    job_id: 8,
    job_title: "Data Analyst",
    job_publisher: "User",
    employer_name: "Data Company 8",
    job_country: "USA",
    employer_logo: "https://via.placeholder.com/150",
    description: "This is a job description for a data analyst position.",
  },
  {
    job_id: 9,
    job_title: "Full Stack Developer",
    job_publisher: "User",
    employer_name: "Tech Company 9",
    job_country: "USA",
    employer_logo: "https://via.placeholder.com/150",
    description:
      "This is a job description for a full stack developer position.",
  },
  {
    job_id: 10,
    job_title: "Mobile Developer",
    job_publisher: "User",
    employer_name: "Tech Company 10",
    job_country: "USA",
    employer_logo: "https://via.placeholder.com/150",
    description: "This is a job description for a mobile developer position.",
  },
];

export { popularJobs };
